language: python
python:
  - "3.6"

before_install:
  - cp trashtalk/settings/dev.py.example trashtalk/settings/dev.py
  - mkdir logs
  - touch logs/trashtalk.log

install:
  - pip install -r requirements/dev.txt

# command to run tests
before_script:
  - createdb trashtalk
#  - psql -c 'create database travis_ci_test;' -U postgres
#  - mysql -e 'GRANT ALL ON trashtalk* TO 'travis'@'localhost';'
#  - mysql -e 'create database trashtalk_test;' -u root
#  - mysql -e 'create database trashtalk;' -u root

script:
  - python manage.py migrate
  - python manage.py test apps

after_script:
  - pylint --rcfile=.pylintrc trashtalk/**/*.py

services:
  - postgresql
#  - mysql