language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

# command to run tests
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script: pytest

service:
  postgresql